### ISSUE TITLE
Margner i headeren

### ISSUE THREAD

**Issue by felskov** [AreWeThereYeti/i-log#10]
Margnerne oppe i headeren lader til at hoppe og danse lidt lige nu - i må gerne lige sørge for det ligner PSD'en lidt mere. Det behøver ikke være pixel-perfect, men lige nu virker det lidt tilfældigt integreret.

**Comment by AreWeThereYeti** [comment]
Til næste projekt skal psden spille med de nødvendige paddings og desuden skal der ligge et specsheet så vi rammer rigtigt første gang. Gridden sejler og derfor sejler implementationen

**Comment by appeardk** [comment]
De mål der er angivet skulle meget gerne stemmer med dem du ser i PSD.  

Photoshop har kun ét guide-grid for hele PSD'en (brugt til "Viser"). Til næste projekt vil jeg lave individuelle PSD'er med hvert sit guide-grid til hver visning. Også gerne et spec sheet.

Jeg antog at I tog udgangspunkt i opsætningen i selve designet. Her mener jeg ikke der er noget der sejler, og margins skulle gerne være konsekvente i de forsk. visninger.
