### ISSUE TITLE
Max Chars

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#100]
Angivelsen af maxChars har tilsyneladende ikke indvirkning på bredden af indtastningsfelter af typen tekstinput. Hvis man fx skriver maxChars 50, så ændres bredden ikke, og der er ikke plads til al den tekst, man kan indtaste som slutbruger

**Comment by AreWeThereYeti** [comment]
Det står ikke i specs at det skal bredden af felterne ændres ved indtastning af maxchars. Men vi estimerer det til en times ekstra work.

**Comment by appeardk** [comment]
Alright, godkendt.

**Comment by AreWeThereYeti** [comment]
Det ser ikke ud til at vi får maxChars fra byggeren, selvom det kan angives i byggeren. Skal vi selv tage fat i Michael eller gør du det, @felskov?

**Comment by AreWeThereYeti** [comment]
Det ser ikke ud til at der er noget loft på i byggeren, men på min 15" skærm fylder det hele skærmen ved 160 characters. Der bør nok være et loft på i byggeren på max 100. Men det kan vi tage i version 2.

**Comment by appeardk** [comment]
Gode pointer. 

Jeg tager fat i Michael :)

**Comment by appeardk** [comment]
I skulle gerne kunne se Max Chars nu. Kan du bekræfte?

Jeg har givet Gyldendal besked om at de ikke bør bruge max chars over 100.

**Comment by jonaslading** [comment]
Der er nu en  'maxChars' attribute i json daten, med den er ikke forbundet til max char input feltet i byggeren endnu. Det har i hvert fald ingen effekt på attributens værdi når der ændres  på den i byggeren

**Comment by appeardk** [comment]
Hey - Michael siger:

Jeg har smidt lidt data ind, så nu skulle det det gerne kunne ses i JSON’en. Jeg får ihvertfald fint data retur fra Gyldendals server.

**Comment by appeardk** [comment]
Tag gerne fat direkte I Michael hvis noget ikke spiller :)

**Comment by jonaslading** [comment]
Jeg fanger michael.
