### ISSUE TITLE
Antal decimaler

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#102]
Estimat ønskes:

Michael har i byggeren introduceret “Antal decimaler” felter til at begrænse antallet af ved inputfelter af typen ’Beregning’. Det er allerede klar til jer i viseren.

Det drejer sig kun om beregning felter i viseren og rapporter, ikke i felter, som brugeren selv indtaster i. Men ’Antal decimaler’-indstilling sat på et beregningsfelt skal også slå igennem, hvis samme beregningsfelt bruges i et diagram.

I byggeren er der  plads til kun én karakter dvs. mellem 0-9 decimaler, så man som redaktør forstår, at man skal skrive ’2’. Hvis man som redaktør skriver ’2’, skal resultatet af beregning altid vises med præcis 2 decimaler – altså uanset om resultatet er 5,55, 5,50 eller 5,00.

**Comment by jonaslading** [comment]
er ordnet
