### ISSUE TITLE
Listerapport - Beskæring af tekster i cellerne

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#104]
Hej 

Kan tekster i cellerne bryde ned på flere linjer i stedet for at blive beskåret af feltet.

Problemet med den nuv. løsning er at der ved 1024x foregår en del beskæring.

**Comment by AreWeThereYeti** [comment]
Jeg har lavet en anden løsning og givet boksen en text-overflow:ellipsis så teksten ender i en ... fremfor at beskære

**Comment by appeardk** [comment]
Alright, det prøver vi at se hvad kunden siger til.

Hvad vil en løsning hvor den bryder ud på flere linjer kræve i stedet for truncation?

**Comment by appeardk** [comment]
Jeg lukker denne da kunden er tilfreds med den nye løsning I har implementeret.
