### ISSUE TITLE
"Påkrævede" felter og validering

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#105]
Estimat ønskes:

1) Felter der i byggeren er markeret som "påkrævet" skal have en orange stjerne efter feltets titel. 

![screen shot 2014-11-25 at 21 37 48](https://cloud.githubusercontent.com/assets/1305280/5191031/64642224-74eb-11e4-9192-44d69d77f81b.png)

2) Beregningsfelter der ikke kan udfyldes/redigeres, skal styles med lys grå baggrund

![screen shot 2014-11-25 at 21 37 51](https://cloud.githubusercontent.com/assets/1305280/5191038/7b49c9da-74eb-11e4-989c-6f5574230d01.png)

3) Hvis der er et eller flere påkrævede felter autoindsættes denne tekst nederst på siden under nederste nederste input:

"Felter markeret med \* skal udfyldes"

4) Validering med følgende prompt "Du kan først gemme, når alle påkrævede felter er udfyldt" .

Både ved første udfyldning og ved redigering af tidligere oprettede

**Comment by AreWeThereYeti** [comment]
Det har taget ca 1 time at implementere.

**Comment by appeardk** [comment]
Okay. Vi skal helst lige cleare estimater på forkant fremover, men jeg er 99% sikker på at jeg kan få den time clearet hos kunden. Jeg Følger op her.

**Comment by appeardk** [comment]
Kunden har godkendt.
