### ISSUE TITLE
Diverse

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#106]
Hvis noget af dette kræver et estimat må du sige til

1) Kan vi disable at arket lukker når man klikker på  gem knappen. Jeg tror Mads vist har bedt om denne rettelse, men kunden har ombestemt sig :)

2) Kan vi fjerne titel kolonnen på "Mine logs" oversigten. Den indsætter de åbenbart selv (som du kan se i det nuv. oplæg).

**Comment by appeardk** [comment]
Er I obs på disse? :)

**Comment by jonaslading** [comment]
Jeg kan lige se på det i eftermiddag/aften. Det simpelt nok ud. 
For at sikre mig jeg forstår det rigtigt.

1)  Her mener du gem knappen når du opretter en ny log, ikke? (billedet neden under)
![screen shot 2014-12-09 at 09 28 45](https://cloud.githubusercontent.com/assets/4579338/5354288/33b0964e-7f86-11e4-85e8-5e922ffbb6af.png)

2) Og her mener du at fjerne titel kolonnen helt fra oversigten i mine logs:
![screen shot 2014-12-09 at 09 25 07](https://cloud.githubusercontent.com/assets/4579338/5354299/6effed3a-7f86-11e4-80da-d5f34c8ab5ac.png)

**Comment by appeardk** [comment]
Yes, det er helt korrekt :) Tusind tak!

**Comment by jonaslading** [comment]
så skulle det spille
