### ISSUE TITLE
Label til venstre for input

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#107]
Estimat ønskes:

Kunden vil i byggeren gerne gøre det muligt at switche mellem den nuværende visning med label over input, og løsningen på dette screenshot hvor label står til venstre for input. Den længste label definerer bredden af labelkolonnen til venstre (op til et max på 250 px).

![venstrestillet](https://cloud.githubusercontent.com/assets/1305280/5210158/057304fa-75c8-11e4-8f0b-c6674788a246.jpg)

**Comment by AreWeThereYeti** [comment]
Layouttet er opsat, men vi mangler noget at lytte på fra byggeren

**Comment by appeardk** [comment]
Okay, det lyder godt. 

Skal der ikke afsættes tid til denne opgave?

**Comment by appeardk** [comment]
Michael følger op med en indstilling i næste udgave af byggeren hvor man kan vælge labelens placering (over eller til venstre) som overordnet indstilling. Jeg følger op med den eksakte parameter værdi her i tråden.

**Comment by AreWeThereYeti** [comment]
Det har taget en time og lave. Jeg misforstod Jonas og troede det var godkendt.

**Comment by appeardk** [comment]
Tak. Jeg er også overbevist om at kunden clearer denne. Jeg følger op her i tråden.

**Comment by appeardk** [comment]
Kunden har godkendt. Jeg har bedt Michael lave en indstilling i byggeren som I kan gribe. Jonas, når du taler med Michael kan I så evt. aftale værdien I skal kigge efter?
