### ISSUE TITLE
Ikke gemte ændringer dialog

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#108]
Når man i en log trykker gem efter at have indtastet data og efterfølgende navigerer tilbage til log-oversigten, får man en dialogboks om, at der er ikke-gemte ændringer. Som sagt: Selvom man har gemt umiddelbart forinden

**Comment by AreWeThereYeti** [comment]
Når man har trykket gem bliver man redirected tilbage til logsoverviewet. Men det kan nogle gange tage lidt tid. Vi implementerer en spinner som bliver vist indtil det er gemt.

**Comment by appeardk** [comment]
OK, jeg beder kunden tjekke om det løser sagen. Kan vi lade den stå åben for nu?

**Comment by AreWeThereYeti** [comment]
yep

**Comment by appeardk** [comment]
Denne er lukket
