### ISSUE TITLE
Rapporter - Indstillinger panel

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#110]
Hey

Kunden har forespurgt på følgende som jeg gerne vil bede om et estimat på:

På listeoversigten skal der vises et tandhjul ikon ved siden af øjet og skraldespanden. 

Samme tandhjul skal vises i topbjælken på selve rapportvisningen.

Klik på tandhjulet folder i begge tilfælde et panel ud der ligner "opret rapport" panelet, hvor periode og titel kan rettes.  

NB. Jeg har spottet at I skriver "Title" over titel feltet i opret rapporter panelet. Kan vi få det rettet til "Titel"

![screen shot 2014-12-03 at 00 29 20](https://cloud.githubusercontent.com/assets/1305280/5273052/724ac562-7a83-11e4-8d2d-7b4cf10d3761.png)

**Comment by AreWeThereYeti** [comment]
Title er fixet og uploadet til develop. Jeg vil tro at det vil tage en 2-3 timer at få lavet. Men kan vi skubbe det lidt, eventuelt til januar, og tage flere tilretninger og forbedringer med i samme omgang hvis der skulle komme nogen?

**Comment by appeardk** [comment]
Tak for fix af "Title".

Det her er vist det sidste "tweak" til v1.0 så vidt jeg ved, men hvis I er lagt ned på denne side af nytår er det forståeligt :) Den næste runde forbedringer kommer først når produktet har været ude og arbejde lidt blandt redaktørerne om 2-3 mdr.

**Comment by appeardk** [comment]
Estimatet på denne er som nævnt godkendt, dog er opgaven reduceret en smule. Der er kun behov for at at indsætte tandhjulet på selve rapport-undersiden, og ikke på liste-oversigten. 

Som I kan se på nedenstående screenshot er panelet identisk med opret-panelet, bortset fra at titlen er ændret til "Indstillinger for rapport", Knappen hedder "Opdater" og ikonet er et tandhjul. 

PSD kan hentes her: http://gyldendal.appear.dk/i-log/Indstillinger.psd.zip

![screen shot 2014-12-23 at 14 50 08](https://cloud.githubusercontent.com/assets/1305280/5538378/05c7871e-8ab3-11e4-8078-5adb556bf885.png)
