### ISSUE TITLE
Datafelt tid

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#111]
Datafelt af typen tid (der findes pt ikke andre typer): adskillelse mellem tallene skal være ‘-' bindestreger ikke ‘:'

**Comment by jonaslading** [comment]
Kun mellem datoen, hvis tid også er defineret e.g. "06:01:2015, 02:57" => "06-01-2015, 02:57"?

Eller også på tiden e.g. "06:01:2015, 02:57" => "06-01-2015, 02-57"?

(jeg antager det første...)

**Comment by appeardk** [comment]
Din antagelse er korrekt.

06-01-2015, 02:57
