### ISSUE TITLE
Oprette rapport

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#113]
Hej 

Når man forsøger at oprette en rapport sker der ikke noget når man klikker på "Gå videre"

Jeg har konstateret det i Chrome til Mac, og Jeppe oplever det her på PC:

http://screencast.com/t/at0T207Q

Jeg vil i øvrigt meget gerne bede om at få ændret teksten på knappen til "Opret"

**Comment by AreWeThereYeti** [comment]
Underligt. Jeg har intet problem i hvert chrome, safari eller firefox. Er det den seneste i tester på?

**Comment by appeardk** [comment]
Hmm, jeg er ret sikker på vi har opdateret sidste gang vi fik besked om at der var et nyt build.

Vi tester her, men jeg ved ikke om der er en måde at konstatere om vi er up to date.

http://gyldendal.felskov.io/i-log/viewer/app/?componentID=540025f23c5b5a07d0570c53&userID=mort088k#/rapporter

Har du evt. en tilsvarende TEST url, så kan jeg evt. lige bekræfte om det også funker her.

**Comment by appeardk** [comment]
Kan I konstatere om mit link er seneste build? 

Og vil I uanset opdatere teksten på opret knappen til "Opret" - takker :)
