### ISSUE TITLE
Forbundet graf

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#114]
Hej 

1) På forbundet graf vises datoerne ikke på x-aksen. Jeg har kigget i byggeren, men det lader ikke til at være fejlkonfigurering, ikke mindst fordi det fungerer fint nok på punktgrafen.

2) Der er et "skalerings" issue på y-aksen der gør at punkterne flyver ud af det synlige område.

Begge kan ses her:

http://screencast.com/t/wjztqUp9

**Comment by jonaslading** [comment]
1) Det har efter min forståelse ikke været en del af designet (i psd'en) at datoen skulle vises på x-aksen på den forbundne graf. Det kan godt laves , men så bliver designet det samme som prik-grafen, med x-akse titlen under aksen. 

2) jeg har ikke kunnet genskabe "skalerings" problemet. har du et url til dette eller kan du plotte data på mort088k brugeren som giver dette? Så kan jeg ordne det.

**Comment by appeardk** [comment]
1) Hmm, det mener jeg. Men ja tak til at gøre det akkurat som prik-grafen.

2) Skaleringsproblemet kan ses her:

1) Åbn: http://gyldendal.felskov.io/i-log/viewer/app/?componentID=540025f23c5b5a07d0570c53&userID=mort088k#/rapporter

2) Vælg første rapport på listen

3) Vælg Punktgraf

![screen shot 2014-12-23 at 14 35 15](https://cloud.githubusercontent.com/assets/1305280/5538268/f0fbdc1a-8ab0-11e4-8928-9cae140669aa.png)

**Comment by jonaslading** [comment]
Da den forbundne graf skalerer dynamisk og punktgrafen ikke gør, kommer det til at se lidt skørt ud når grafer er udstrakte som dit eksempel:  
![screen shot 2014-12-23 at 17 35 52](https://cloud.githubusercontent.com/assets/4579338/5540286/97df912a-8aca-11e4-818e-739d5543d5a3.png)

Alternativt kunne jeg lave akseindikationer ved hver dag, sådan her:
![screen shot 2014-12-23 at 17 41 30](https://cloud.githubusercontent.com/assets/4579338/5540353/19211312-8acb-11e4-957a-c259db829281.png)

**Comment by appeardk** [comment]
Ka du evt. lige kigge forbi Skype, så vi kan vende det hurtigt?

**Comment by appeardk** [comment]
Jeg synes dit forslag give rigtig fin mening. 

I eksemplet ovenfor vil 12/10 så stå under punkerne til venstre? Og vil den kun vise de dage på aksen hvor der er aktive indtastninger?

**Comment by appeardk** [comment]
@jonaslading 

Kunden er cool med løsningen vi talte om hvor vi kun viser en dato på aksen for flere punkter med samme dato. 

Vi skal ikke lave den mere avancerede model hvor vi kiggede på afstanden mellem punkter som vi talte om.

**Comment by appeardk** [comment]
Vil du estimere følgende to justeringer til dette issue:
- X-placeringen af de enkelte punkter er bestemt af Unix-timestamp – og vil dermed variere for punkter med samme dato men forskelligt tidspunkt (Hvis det ikke er sådan vi allerede gør?)
- Ved mouseover hhv klik (touch på tablet) – vises fuldt tidsformat: dd:mm:yyyy, hh:mm ved siden af punktet.

**Comment by appeardk** [comment]
Som aftalt hermed et oplæg på den lille kasse der placeres bag punktet når det atkiveres med mouseover (el. touch på tablet).

![image002](https://cloud.githubusercontent.com/assets/1305280/5710528/4dcdd8f6-9aa3-11e4-92c2-be54dab06b07.png)

**Comment by appeardk** [comment]
De 4 timer her er også godkendt @jonaslading
