### ISSUE TITLE
Graf x-akse dato

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#115]
Estimer evt følgende:

Forkerte dato-angivelser på x-aksen i punkt-graf + forkert datoangivelse ud for registreringer i Mine logs. 

I den aktive i-log kan man af rapporten aktivitetsoversigt se, at aktiviteterne fordeler sig ud over datoerne 9., 10., 11. og 12. december. Men i punktgraf og Mine logs er det angivet, at alle registreringer er foretaget 9. december. Angiveligt fordi der gøres brug af dato-stempel fra data-record i stedet for dato angivet af brugeren. Jeg 'frygter' lidt, at det samme gør sig gældende for rapporternes medtagelse af registreringer. Kan det fikses? 

Alternativt tror jeg, vi er nødt til at disable muligheden for redigering af datofeltet. Ellers bliver det for forvirrende. Det optimale vil være, hvis vi kan tjekke op på, om der findes et dato-felt i en log - og i så fald bruge den angivne dato frem for db-datostemplet.

**Comment by jonaslading** [comment]
Det er rigtigt at graf og mine logs bruger en enkelte logs timestamp (created at). Jeg kan godt lave et tjek for om der er et data felt også bruge dato'e, i dette istedet for. Men det vil lige nu nok betyde at man kun vil have ét datafelt per log, og at data feltet bliver dedikeret til dette.
vil estimere 3 timer til dette.

**Comment by appeardk** [comment]
Modtaget. Jeg tager estimatet og dit input vedr. "max antal datafelter" videre til kunden, tak.

**Comment by appeardk** [comment]
Hej Jonas

Jeg har aftalt med Mads lige at afslutte de issues der allerede findes her på Github. Fremover vil evt. nye issues blive oprettet på GitLab.

Kunden har besluttet sig for en lidt anderledes løsning. Vil du estimere følgende:

De introducerer et obligatorisk obligatorisk tidspunkt felt som indgår i alle ark, og som altid vises før de manuelt oprettede inputfelter.

I byggeren får man følgende indstillinger:
- Label (default = ’Tidspunkt’),
- Vis i oversigt (default = true)
- Vis i logs (default = true)
- Redigerbart, (default = true)
- Format (default = dd:mm:yyyy)

I oversigten (Mine logs) skal tidspunkt vises længst til venstre
I de enkelte logs skal tidspunktet vises før de redaktør-oprettede input-felter

**Comment by appeardk** [comment]
Michael har lavet sin del og smidt det op, så det er nu med i feed'et:

timeInput":{"showInOverview":true,"showInLog":true,"editable":true,"format":"date","label":"Tidspunkt"}},

**Comment by appeardk** [comment]
Den time du estimerede er godkendt.

**Comment by jonaslading** [comment]
når du skriver:
"I oversigten (Mine logs) skal tidspunkt vises længst til venstre"
menes der så istedet for den eksisterende dato kolonne? eller før denne?

og har jeg forstået det rigtigt at dette tids input skal være det som graferne (punkt og linie) skal baseres på? eller skal de fortsat være baseret på timestampet for hvornår loggen blev oprettet?

**Comment by appeardk** [comment]
Der menes i stedet for den eksisterende dato kolonne.

Ja, det er korrekt forstået at det er dette nye tidspunkt som punkt og linie skal baseres på.
