### ISSUE TITLE
Rækkefølge af rapporter

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#116]
Får I info om rækkefølge af rapporterne med i feed'et fra byggeren? Og hvad vil det i så fald kræve at lade dette bestemme rækkefølgen i menubjælken. 

Estimer gerne :)

![screen shot 2014-12-16 at 00 03 04](https://cloud.githubusercontent.com/assets/1305280/5445753/f0c3de1e-84b6-11e4-8d56-c12610ba384c.png)

**Comment by jonaslading** [comment]
Det er ordnet
