### ISSUE TITLE
Design - Listeoversigt

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#36]
Ikonerne:
-  Skal gerne gerne ligne dem fra PSD'en mere
- Størrelsen i selve listeoversigten er for lille
- Renderingen af pen og skraldespand er meget ringe ift. PSD. Se gerne mit.gyldendal.dk (MG)
- Farven på symbolerne i ikonet er sort, i PSD og MG er #383838
- Tjek gerne størrelsen på ikonerne ift. PSD fx er spørgsmålstegnet markant mindre og sidder lidt mystisk v-alignet :)

Fonte:
- Bruges fonten "Franklin" på alle tekst-elementer? Det skal den gerne.
- Området under listen er i PSD #383838 men i web-versionen er det hvidt. 
- Teksten "Dato" i den orange filterbjælke er i PSD hvid, men i web-versionen grålig?
- Tekst i Dato kolonnen i "Mine rapporter" er bolded
- Datoen er orange i listeoversigten
- Der mangler pil ud for den kolonne der aktuelt sorteres på, se "Dato" og "Fra dato" i designet eller MG.

**Comment by AreWeThereYeti** [comment]
Jeg har fixet mange af de her @jonaslading . Men da successkriterierne for de her er lidt vage, så skal vi lige checke op dem alle. Fonten er integreret, rendering er pen og skraldepan er ændret, farverne på symbolerne er ændret, margin på top ikonerne er ændret, størrelsen på spørgsmålstegnet er ændret osv.
