### ISSUE TITLE
Listeoversigter - Design

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#40]
Et par gengangere fra sidst som lader til at være blevet lukket:
- Emnerne på listen er 16px, i PSD er det pkt 14 - gælder alle kolonner
- Dato og Titel i den hvide bjælke over listen er pkt 16, i PSD er det pkt 14
- Dato / Titel mangler den lille pil der indikerer hvilken kolonne der er sorteret på som i PSD
- Den kolonne der aktivt sorteres på er orange som i PSD
- Kan filter/tragt symbolet og +’et blive bare 2-px mindre?
- Kan øje-symbolet blive 2px mindre (i bredden, højde proportionelt)
- Under sidste række i listeoversigten mørkegrå farve. Det skal bare være samme farve som selve listen, se evt. mit gyldendal.
- Kan vi få “rediger”-link på titel kolonen inkl. underline ved mouse som på MG?

**Comment by jonaslading** [comment]
mangler:
· Kan filter/tragt symbolet og +’et blive bare 2-px mindre?
· Kan øje-symbolet blive 2px mindre (i bredden, højde proportionelt)
· Kan vi få “rediger”-link på titel kolonen inkl. underline ved mouse som på MG? (er ikke helt sikker på hvad her menes)

Dato og Titel i den hvide bjælke over listen er pkt 18 i PSD'en ikke pkt 14, tænker det er en slå fejl

**Comment by appeardk** [comment]
· Kan filter/tragt symbolet og +’et blive bare 2-px mindre?
· Kan øje-symbolet blive 2px mindre (i bredden, højde proportionelt)
MN: Mangler du yderligere input til disse? 

· Kan vi få “rediger”-link på titel kolonen inkl. underline ved mouse som på MG? (er ikke helt sikker på hvad her menes)
MN: Her menes at man ved klik på titlen i "Titel" kolonnen bliver taget til samme side som man kommer til ved klik på rediger-blyanten. Gerne med underline ved mouseover på titlen. Se evt. MG.

Dato og Titel i den hvide bjælke over listen er pkt 18 i PSD'en ikke pkt 14, tænker det er en slå fejl
MN: Ja, korrekt. De skal bare være 18 pkt.

**Comment by jonaslading** [comment]
MN: Mangler du yderligere input til disse?
nej det var bare interne noter :)

**Comment by appeardk** [comment]
Alrighty, synes det begynder at se rigtig godt ud :) Tak
