### ISSUE TITLE
Franklin

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#43]
Det ligner ikke vi bruger Franklin fonten alle steder endnu. Ved sammenligning med MG renderer fonten i hvert fald ret anderledes?

**Comment by AreWeThereYeti** [comment]
Umiddelbart skulle franklin gerne være brugt alle steder. Men den konfiguration der bliver indlæst bruger arial, så franklin bliver selvfølgelig overskrevet hvor det er tilfældet

**Comment by appeardk** [comment]
Til præsentationen for Gyldendal kan vi så switche til Franklin?

**Comment by jonaslading** [comment]
Som det er nu kan man ikke vælge Franklin fonten igennem michaels bygger, men jeg kan lige overskrive de komponent settings vi får ind, så fonten blir Franklin.

**Comment by appeardk** [comment]
Kanon, tak!
