### ISSUE TITLE
Rapport - Lagkagediagram

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#51]
- Kan vi få samme farver som PSD? Skal jeg evt. levere flere farvekoder?
- Gerne "Udfaldsrum" titel over kage-definitionen som PSD. 
- Ryk gerne "Udfaldsrum" og de følgende punker ned så den flugter med top af grafen

**Comment by jonaslading** [comment]
@appeardk : Hey morten, Du må meget gerne levere flere farver, ellers vil de samme farver blive genbrugt hvis der er mange input elementer.

![screenshot2014-10-30at11 35 04](https://cloud.githubusercontent.com/assets/4579338/4841997/9b0ca736-6020-11e4-8adc-b2339f12861d.png)

**Comment by appeardk** [comment]
#e42b41
#a965dd
#2be435
#dcdd65
#2be4de
#ffe40f
#e4902b
#65a6dd
#2b4fe4
#e4902b
#65ddb2
#e4532b
#e4902b
#632be4
#2be435
#2be4c0
#2b8de4
#e42bca
#e42b8c
#fa2114
