### ISSUE TITLE
"Gå direkte til indtastningssiden"

### ISSUE THREAD

**Issue by felskov** [AreWeThereYeti/i-log#69]
Jeg er noget usikker på hvorfor der kommer en confirm-dialog der siger "Gå direkte til indtastningssiden" - måske er det med vilje? Det ser i hvert fald ret sjovt ud, især fordi det bagvedliggende UI ikke er renderet færdigt endnu.

**Comment by AreWeThereYeti** [comment]
Det kan være vi har misforstået specifikationen, men der står : "Når brugeren åbner viseren undersøges det om vedkommende har nogen gemte indtastninger. Såfremt der er gemte indtastninger, vises en dialog hvori brugeren kan vælge om han ønsker at oprette en ny indtastning eller gå til oversigtssiden. Hvis der ikke er gemte indtastninger, hoppes direkte til indtastningssiden." Men ja, det er underligt. Væk med det?

**Comment by appeardk** [comment]
@jonaslading - Lad os bare udkommentere denne :)
