### ISSUE TITLE
Hashtag i url /HTML5 mode

### ISSUE THREAD

**Issue by AreWeThereYeti** [AreWeThereYeti/i-log#77]
@felskov du skrev at der var nogle problemer med componentId i url'en hvis det står før Hashtag.  Du skriver i mailen "Jeg blev lige opmærksom på følgende: ?componentID=x&userID=x kan ikke stå før havelågen, da disse informationer skal bruges i PHP-regi for at verificere at brugeren tilgår siden med en korrekt signature. Kan i rette det til i jeres ende?" 
Men lige nu står # før component id. Er det et problem? For vi kan fjrner det helt hvis det er

**Comment by felskov** [comment]
Ja, meningen er at de skal kunne gribes af PHP - og det kan alt efter hashtagget ikke :-) Så hvis i bare kan fjerne den, så er det super fint.
