### ISSUE TITLE
Krydsbrowser - PC

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#79]
Hej 

På Chrome PC ser sker der følgende på denne URL (som virker fint i Safari og Chrome til Mac):

http://gyldendal.felskov.io/i-log/viewer/app/?componentID=540025f23c5b5a07d0570c53&userID=mort088k#/

![screen shot 2014-11-14 at 00 43 15](https://cloud.githubusercontent.com/assets/1305280/5038962/51054008-6b97-11e4-8c24-2f59476c1779.png)

**Comment by appeardk** [comment]
IE 11

![screen shot 2014-11-14 at 00 46 38](https://cloud.githubusercontent.com/assets/1305280/5038996/bebf93f0-6b97-11e4-982f-e4d4e720e7b5.png)

Fonten ser også sjov i topbjælken på dette screenshot.

**Comment by appeardk** [comment]
IE9

![screen shot 2014-11-14 at 00 46 08](https://cloud.githubusercontent.com/assets/1305280/5038999/c85b5872-6b97-11e4-893b-f180e6814006.png)

**Comment by felskov** [comment]
Det skyldes at ?componentID=... ikke kan læses rigtigt ved brug af $location.search()... - da den læser parametre der står efter havelågen når html5-mode er disablet. Jeg har rettet dette på staging-miljøet, det drejer sig om følgende lille fix i app/scripts/services/getdatascervice.js:

```
//finds userID and Component id in url
var tmpComponentID = (window.location.href.split('componentID=')[1] || '').split('&')[0].split('#')[0] || null,
  tmpUserID = (window.location.href.split('userID=')[1] || '').split('&')[0].split('#')[0] || null;

if(angular.isDefinedOrNotNull(tmpComponentID) && angular.isDefinedOrNotNull(tmpUserID)){
localStorage.userID =  tmpUserID;
localStorage.componentID =  tmpComponentID;
}
var componentID = localStorage.componentID;
```

Vil i indføre det i GitHub repository så vi lige før kørt det ordentligt ind i kodebasen?

Derudover lader der dog til at være nogen grundlæggende bugs ved første indlæsning af siden - og IE9 fungerer i hvert fald ikke (jeg tror måske i mangler at indlæse noget es5-shim ved genenmgang af fejl-loggen).

**Comment by appeardk** [comment]
IE8 har også problemer.

**Comment by AreWeThereYeti** [comment]
Crossbrowser problemerne skulle være fixet nu. Så i den master der kommer op snart kan du indføre koden.

**Comment by appeardk** [comment]
Det lader ikke til at vi har flere crossbrowser issues.
