### ISSUE TITLE
Visning af label / enhed mangler ud for beregninger

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#86]
Visning af label / enhed mangler ud for beregninger

**Comment by AreWeThereYeti** [comment]
Kan du specificere det lidt nærmere?

**Comment by felskov** [comment]
Hvis du kigger på de vedhæftede screenshots, så kan du se at der er angivet enhedsangivelser for alle tre felter i byggeren - men den fremgår kun af tal-inputtet i viseren. Jeg antager det er fordi i mangler at rendere det ud for beregningsfelter.

![skaermbillede 2014-11-18 kl 17 15 25](https://cloud.githubusercontent.com/assets/1436954/5091062/ae860da4-6f46-11e4-8ef3-67bec80161a6.png)
![skaermbillede 2014-11-18 kl 17 15 57](https://cloud.githubusercontent.com/assets/1436954/5091061/ae808aa0-6f46-11e4-9627-e68cba5a7b13.png)
