### ISSUE TITLE
Overflow-scroll på rapport-visning uden beregninger

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#90]
Vi bør undgå overflow-scroll på rapport-visning uden beregninger.

**Comment by AreWeThereYeti** [comment]
Beregninger overskriften bliver ikke vist hvis der ikke er nogle beregninger. Så hvis det er det du mener så er det fixet nu

**Comment by felskov** [comment]
Den er blevet løst sammen med fejlen hvor "beregninger"-overskriften blev vist uden der var nogen aktive beregninger.
