### ISSUE TITLE
Fejl ved indlæsning af deeplink til rapporter

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/i-log#93]
Nogen gange sker der en fejl hvor "reports is undefined", er der en race condition hvor i renderer før bagvedliggende data er indlæst?

**Comment by AreWeThereYeti** [comment]
Jeg er ikke helt sikker på jeg forstår. Jeg vil antage at det er når den får en fejl fra serveren for det sker nogle gange uden varsel. Men hvis du falder over fejlen igen så tag lige en screenshot af konsolen og evt beskrivelse så vi kan se om der er noget vi kan gøre ved det

**Comment by felskov** [comment]
Hej Mikkel. Nej, der blev ikke meldt en fejl 500 på API'et - men læg den på is indtil vi evt. oplever det igen, det kan også have været løst med nogen af de ting i har deploy'et i løbet af de sidste dage. Jeg genopretter issuet, hvis vi oplever det igen :-)
